=== Eric212/2DAM/DI/Restaurante.dtd
<!ELEMENT RESTAURANTE (MENU, CARTA, PLANTILLA)>

<!-- Elementos de RESTAURANTE -->
<!ELEMENT MENU (PRIMERO+, SEGUNDO+, TERCERO+,(POSTRE+|CAFE),PRECIO_MENU)>
<!ELEMENT CARTA (PLATO_CARTA+)>
<!ELEMENT PLANTILLA (EMPLEADO+)>

<!-- Elementos de MENU -->
<!ELEMENT PRECIO_MENU (#PCDATA)>
<!ELEMENT PRIMERO (#PCDATA)>
<!ELEMENT SEGUNDO (#PCDATA)>
<!ELEMENT TERCERO (#PCDATA)>
<!ELEMENT POSTRE (#PCDATA)>
<!ELEMENT CAFE (#PCDATA)>

<!-- Elementos de CARTA -->
<!ELEMENT PLATO_CARTA (NOMBRE_PLATO,PRECIO_PLATO)>

<!-- Elementos de PLATO_CARTA-->
<!ELEMENT NOMBRE_PLATO (#PCDATA)>
<!ELEMENT PRECIO_PLATO (#PCDATA)>

<!-- Elementos de PLANTILLA -->
<!ELEMENT EMPLEADO (NOMBRE_EMPLEADO,TURNO+)>

<!-- Elementos de NOMBRE_EMPLEADO -->
<!ELEMENT NOMBRE_EMPLEADO (#PCDATA)>
<!ATTLIST EMPLEADO CARGO (Camarero|Cocinero) #REQUIRED>
<!ELEMENT TURNO (#PCDATA)>

=== Eric212/2DAM/DI/Restaurante.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RESTAURANTE SYSTEM "Restaurante.dtd">
<?xml-stylesheet href="xsl.xsl" type="text/xsl"?>
<RESTAURANTE>
    <MENU>
        <PRIMERO>Ensalada Valenciana</PRIMERO>
        <SEGUNDO>Huevo de codorniz con tomacat y atun</SEGUNDO>
        <TERCERO>Tallarines de sepia</TERCERO>
        <POSTRE>Tarta de queso</POSTRE>
        <POSTRE>Tarta de calbaza</POSTRE>
        <POSTRE>Panacota</POSTRE>
        <PRECIO_MENU>19,50€</PRECIO_MENU>
    </MENU>
    <CARTA>
        <PLATO_CARTA>
            <NOMBRE_PLATO>Arroz del Senyoret</NOMBRE_PLATO>
            <PRECIO_PLATO>18,50€/Por persona</PRECIO_PLATO>
        </PLATO_CARTA>
        <PLATO_CARTA>
            <NOMBRE_PLATO>Arroz a banda</NOMBRE_PLATO>
            <PRECIO_PLATO>12,50€/Por persona</PRECIO_PLATO>
        </PLATO_CARTA>
        <PLATO_CARTA>
            <NOMBRE_PLATO>Denton</NOMBRE_PLATO>
            <PRECIO_PLATO>55€/El Kg</PRECIO_PLATO>
        </PLATO_CARTA>
    </CARTA>
    <PLANTILLA>
        <EMPLEADO CARGO="Camarero">
            <NOMBRE_EMPLEADO>Gabriel</NOMBRE_EMPLEADO>
            <TURNO>10:00-17:00</TURNO>
        </EMPLEADO>
        <EMPLEADO CARGO="Cocinero">
            <NOMBRE_EMPLEADO>Angy</NOMBRE_EMPLEADO>
            <TURNO>10:00-17:00</TURNO>
        </EMPLEADO>
        <EMPLEADO CARGO="Camarero">
            <NOMBRE_EMPLEADO>Puri</NOMBRE_EMPLEADO>
            <TURNO>19:30-00:00</TURNO>
        </EMPLEADO>
        <EMPLEADO CARGO="Cocinero">
            <NOMBRE_EMPLEADO>Sergio</NOMBRE_EMPLEADO>
            <TURNO>19:30-00:00</TURNO>
        </EMPLEADO>
    </PLANTILLA>
</RESTAURANTE>
